### PR TITLE
Added missing validator translations for fr_FR

### PR DESCRIPTION
**Pull request by mmetayer**
Updates validation message translations and adds missing ones for fr_FR locale, like in PR's #6 and #7

### CODE REVIEW

**Comment by Maks3w** [comment]
There are conflicts. Could you rebase?

**Comment by mmetayer** [comment]
@Maks3w : Seems I can't push after rebasing. Should I force-push or merge develop instead ?
(or even close this PR and open a new one from the right branch)?

**Comment by weierophinney** [comment]
Force push to your branch. That's the typical workflow. :smile:

**Comment by samsonasik** [comment]
there are articles for rebase steps:
- http://akrabat.com/the-beginners-guide-to-rebasing-your-pr/
- https://samsonasik.wordpress.com/2015/09/16/practical-git-4-rebasing-conflicted-task-branch-against-primary-branch/

**Comment by mmetayer** [comment]
Thanks, that's just what I did, but I wasn't sure if a force-push was going to mess something up somehow. I'll know from now on :wink:

**Comment by Maks3w** [comment]
Merged https://github.com/zendframework/zend-i18n-resources/commit/0a7dda3bbde6998d25ab950f38b8aa7a00833d14

**Pull request closed without merging**
