### PR TITLE
Small typo fix

### PR DESCRIPTION
**Pull request by xorock**

### CODE REVIEW

**Comment by froschdesign** [comment]
We need a polish speaking person to reviewing it.

**Comment by xorock** [comment]
I'm native polish speaker. You can verify it by comparing to line above, translation for "No record matching the input was found".

**Comment by froschdesign** [comment]
> I'm native polish speaker.

I saw this, but for translations we need another one – the Two-man rule.

> You can verify it by comparing to line above

In this case it is simple! 😉

**Review by froschdesign — APPROVED** [review]

**Review by michalbundyra — APPROVED** [review]

**Comment by weierophinney** [comment]
Thanks, @xorock! Merged to develop for release with 2.6.0.

**Pull request closed without merging**
