### PR TITLE
pt_BR translation update

### PR DESCRIPTION
**Pull request by weckx**
This PR updates validators messages in the pt_BR translation. Since the last review in 2013 several new validators have been added and many messages have changed. The file is now synced with the english translation.

### CODE REVIEW

**Comment by Maks3w** [comment]
Due the merge of #7 this now conflicts. Please rebase

**Comment by weckx** [comment]
Rebased. Seems to merge correctly now.

**Comment by weierophinney** [comment]
@Maks3w Please merge to develop as well.

**Comment by Maks3w** [comment]
It's merged, bug GH does not display the commit in the PR

**Pull request merged**
