### PR TITLE
[ZF3] copy languages/Zend_Validate.php to languages/Zend_Validator.php

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by weierophinney** [comment]
I disagree; making that change will break existing applications, as they will have to update the translator to indicate the file to look for.

**Comment by samsonasik** [comment]
@weierophinney  this is for zf3 that I copy from zf2 repo that marked as zf3...

**Comment by samsonasik** [comment]
I updated the title for ZF3, please re-open the pr

**Comment by samsonasik** [comment]
@weierophinney  refs https://github.com/zendframework/zf2/pull/4774 for zf3

**Comment by weierophinney** [comment]
@samsonasik I still disagree, as it is yet another migration vector that will cause problems for end users. As it's not a necessary/required architectural change, I'd prefer we leave it as-is to minimize the number of changes developers will need to make to migrate from 2 to 3.

**Comment by grizzm0** [comment]
I do not agree here @weierophinney. The files where never easy to use without copying them into your own project before this repo (which was created in the 2.5 spit I assume?)

People who didn't copy it into their own project probably had a relative path to the vendor directory. So they would need to update anyway. Or perhaps you're talking about the migration from 2.5 to 3.0 which would be a really small scale of people.

Also talked to @DASPRiD about I18n resources earlier today and he suggested to move the resources to zend-validator-i18n and zend-capcha-i18n.

Another problem I see and I hope will be fixed for 3.0 is the folder names for the language files. The current language files are named after the region, not the language.

As these are language files and has nothing to do with regions they should be named after languages. If I have a Swedish speaking Finish visitor (Yes, parts of Final speak Swedish) they would have the locale sv_FI. With the current naming there's no way for me to change the validation messages to their language (Swedish) without creating an internal mapping.

But then we get to another problem. What about en_GB and en_US (and other languages that depend on region).

**Pull request closed without merging**
